steps:
  # Step 1: Run unit tests
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Running unit tests ==="
        dotnet test EmailFixer.sln \
          --configuration Release \
          --no-build \
          --verbosity normal

  # Step 2: Build API Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/emailfixer-api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/emailfixer-api:latest'
      - '-f'
      - 'EmailFixer.Api/Dockerfile'
      - '.'
    id: 'build-api'

  # Step 3: Push API image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/emailfixer-api:$SHORT_SHA'
    id: 'push-api'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/emailfixer-api:latest'
    id: 'push-api-latest'

  # Step 4: Deploy API to Cloud Run
  - name: 'google.cloud.cli'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'emailfixer-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/emailfixer-api:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:emailfixer-postgres'
      - '--set-env-vars'
      - 'ASPNETCORE_ENVIRONMENT=Production'
      - '--set-secrets'
      - 'ConnectionStrings__DefaultConnection=db-connection:latest'
      - '--set-secrets'
      - 'Paddle__ApiKey=paddle-api-key:latest'
      - '--set-secrets'
      - 'Paddle__VendorId=paddle-vendor-id:latest'
      - '--set-secrets'
      - 'Paddle__WebhookSecret=paddle-webhook-secret:latest'
      - '--set-secrets'
      - 'GoogleOAuth__ClientId=google-oauth-client-id:latest'
      - '--set-secrets'
      - 'GoogleOAuth__ClientSecret=google-oauth-client-secret:latest'
      - '--set-secrets'
      - 'Jwt__Secret=jwt-secret:latest'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '60s'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--quiet'
    id: 'deploy-api'
    waitFor: ['push-api-latest']

  # Step 5: Test API health endpoint
  - name: 'gcr.io/cloud-builders/gke-deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting for API to be ready..."
        sleep 10
        API_URL=$(gcloud run services describe emailfixer-api \
          --region us-central1 \
          --format 'value(status.url)')
        echo "API URL: $API_URL"
        echo "Testing API health endpoint..."
        curl -f "$API_URL/health" || exit 1
    id: 'test-api'
    waitFor: ['deploy-api']

  # Step 6: Build Client Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/emailfixer-client:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/emailfixer-client:latest'
      - '-f'
      - 'EmailFixer.Client/Dockerfile'
      - '.'
    id: 'build-client'
    waitFor: ['test-api']

  # Step 7: Push Client image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/emailfixer-client:$SHORT_SHA'
    id: 'push-client'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/emailfixer-client:latest'
    id: 'push-client-latest'

  # Step 8: Deploy Client to Cloud Run
  - name: 'google.cloud.cli'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'emailfixer-client'
      - '--image'
      - 'gcr.io/$PROJECT_ID/emailfixer-client:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '30s'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--concurrency=80'
      - '--quiet'
    id: 'deploy-client'
    waitFor: ['push-client-latest']

  # Step 9: Test Client deployment
  - name: 'gcr.io/cloud-builders/gke-deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Testing Client deployment..."
        CLIENT_URL=$(gcloud run services describe emailfixer-client \
          --region us-central1 \
          --format 'value(status.url)')
        echo "Client URL: $CLIENT_URL"
        echo "Testing client loads HTML..."
        curl -f "$CLIENT_URL" | grep -q "<!DOCTYPE html>" || exit 1
        echo "Testing WASM files..."
        curl -f "$CLIENT_URL/_framework/blazor.webassembly.js" -I | grep -q "200" || exit 1
        curl -f "$CLIENT_URL/_framework/blazor.boot.json" -I | grep -q "200" || exit 1
    id: 'test-client'
    waitFor: ['deploy-client']

  # Step 10: Summary
  - name: 'google.cloud.cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "✅ DEPLOYMENT COMPLETE"
        echo "=========================================="
        API_URL=$(gcloud run services describe emailfixer-api --region us-central1 --format 'value(status.url)')
        CLIENT_URL=$(gcloud run services describe emailfixer-client --region us-central1 --format 'value(status.url)')
        echo ""
        echo "API Service: $API_URL"
        echo "Client Service: $CLIENT_URL"
        echo ""
    id: 'summary'
    waitFor: ['test-client']

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'
