# Cloud Build Configuration for Email Fixer
# This file defines the build steps for deploying to Google Cloud Platform

steps:
  # Step 1: Build and test the .NET application
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    id: 'restore'
    entrypoint: 'dotnet'
    args: ['restore', 'EmailFixer.sln']

  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    id: 'build'
    entrypoint: 'dotnet'
    args: ['build', 'EmailFixer.sln', '--configuration', 'Release', '--no-restore']
    waitFor: ['restore']

  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    id: 'test'
    entrypoint: 'dotnet'
    args: ['test', 'EmailFixer.sln', '--configuration', 'Release', '--no-build', '--verbosity', 'normal']
    waitFor: ['build']

  # Step 2: Build Docker image for API
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/emailfixer-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/emailfixer-api:latest'
      - '-f'
      - 'EmailFixer.Api/Dockerfile'
      - '.'
    waitFor: ['test']

  # Step 3: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api-image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/emailfixer-api:$COMMIT_SHA'
    waitFor: ['build-api-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/emailfixer-api:latest'
    waitFor: ['build-api-image']

  # Step 4: Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'emailfixer-api'
      - '--image=gcr.io/$PROJECT_ID/emailfixer-api:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=$_CLOUDSQL_INSTANCE'
      - '--set-env-vars=ASPNETCORE_ENVIRONMENT=Production'
      - '--set-secrets=ConnectionStrings__DefaultConnection=db-connection:latest'
      - '--set-secrets=Paddle__ApiKey=paddle-api-key:latest'
      - '--set-secrets=Paddle__VendorId=paddle-vendor-id:latest'
      - '--set-secrets=Paddle__WebhookSecret=paddle-webhook-secret:latest'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=60s'
      - '--max-instances=10'
      - '--min-instances=0'
    waitFor: ['push-api-image']

  # Step 5: Get Cloud Run service URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-api-url'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services describe emailfixer-api \
          --region=$_REGION \
          --format='value(status.url)' > /workspace/api-url.txt
    waitFor: ['deploy-api']

  # Step 6: Build Blazor Client
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    id: 'build-client'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        API_URL=$(cat /workspace/api-url.txt)
        dotnet publish EmailFixer.Client \
          -c Release \
          -o /workspace/publish \
          /p:ApiBaseUrl=$API_URL
    waitFor: ['get-api-url']

  # Step 7: Deploy Client to Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-client'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m rsync -r -d /workspace/publish/wwwroot gs://$_CLIENT_BUCKET
    waitFor: ['build-client']

  # Step 8: Invalidate CDN cache (optional, if using CDN)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'invalidate-cdn'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ ! -z "$_CDN_URL_MAP" ]; then
          gcloud compute url-maps invalidate-cdn-cache $_CDN_URL_MAP --path "/*" || true
        fi
    waitFor: ['deploy-client']

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/emailfixer-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/emailfixer-api:latest'

# Substitution variables (set in Cloud Build trigger or via --substitutions flag)
substitutions:
  _REGION: 'us-central1'
  _CLOUDSQL_INSTANCE: 'emailfixer-prod:us-central1:emailfixer-db'
  _CLIENT_BUCKET: 'emailfixer-client'
  _CDN_URL_MAP: ''  # Optional: set if using Cloud CDN

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'

# Build timeout (30 minutes)
timeout: '1800s'

# Tags for organizing builds
tags: ['emailfixer', 'production', 'cloud-run']
